// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using market.DbContextFolder;

#nullable disable

namespace market.Migrations
{
    [DbContext(typeof(MarketDbContext))]
    [Migration("20250617172048_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyMarketLibrary.Models.Cart", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("userid")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("userid");

                    b.ToTable("carts");
                });

            modelBuilder.Entity("MyMarketLibrary.Models.CartItem", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("cart_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("cartid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("item_id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("itemid")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("cartid");

                    b.HasIndex("itemid");

                    b.ToTable("carts_item");
                });

            modelBuilder.Entity("MyMarketLibrary.Models.Item", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("items");
                });

            modelBuilder.Entity("MyMarketLibrary.Models.User", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("MyMarketLibrary.Models.Cart", b =>
                {
                    b.HasOne("MyMarketLibrary.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userid");

                    b.Navigation("user");
                });

            modelBuilder.Entity("MyMarketLibrary.Models.CartItem", b =>
                {
                    b.HasOne("MyMarketLibrary.Models.Cart", "cart")
                        .WithMany()
                        .HasForeignKey("cartid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMarketLibrary.Models.Item", "item")
                        .WithMany()
                        .HasForeignKey("itemid");

                    b.Navigation("cart");

                    b.Navigation("item");
                });
#pragma warning restore 612, 618
        }
    }
}
